name: YOKAI CI
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install SQLx.
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli --no-default-features --features native-tls,postgres
      - name: Connect to PostgreSQL.
        run: sqlx database create --database-url postgres://postgres:postgres@postgres:5432/yokai
      - name: Run migrations.
        run: |
          cd yokai-backend
          sqlx migrate run --database-url postgres://postgres:postgres@postgres:5432/yokai
      - name: "Run unit tests."
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./yokai-backend/Cargo.toml -- --test-threads=1
        env:
          YOKAI_DB_URL: postgres://postgres:postgres@postgres:5432/yokai
      - name: "Build Docker image."
        run: docker build -t yb ./yokai-backend --platform linux/amd64
